### ISSUE TITLE
GL and SDL <didx> option does nothing

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#168] opened 2021-07-21 22:56 UTC
I was looking deep into the code but I have not been able to see how the display index didx is used.  The help reports that its a display index, I am assuming this is to be used to put the video output on to another display, but nothing seems to work.  1, :1, :1.0, HDMI-1 etc.... nothing works.  Suggestions or is this a feature that is there, but not for use on linux?

`SDL options:
	-d sdl[[:fs|:d|:display=<didx>|:driver=<drv>|:novsync|:renderer=<ridx>|:nodecorate|:fixed_size[=WxH]|:window_flags=<f>|:pos=<x>,<y>|:keep-aspect]*|:help]
	where:
		       d - deinterlace
		      fs - fullscreen
		  <didx> - display index
		   <drv> - one of following: x11, mir, wayland, dummy
	     keep-aspect - keep window aspect ratio respecive to the video
	         novsync - disable sync on VBlank
	      nodecorate - disable window border
	fixed_size[=WxH] - use fixed sized window
	    window_flags - flags to be passed to SDL_CreateWindow (use prefix 0x for hex)
		  <ridx> - renderer index: 0 - opengl, 1 - opengles2, 2 - software`
		  
		  
Update: seems like POS for position doesn't work either...
Update: when passing the FS command, the POS command doesn't work.  If I just use the sdl or gl command and POS option,  I can move the window around my desktop multiple screens, but if I pass FS command it will only do FS on one screen, which is not the screen I want it on. I can place the window onto any screen I like as long as I don't pass the NODECORATE and FS options.  The problem is there is a window border now on the video.
Update: Looks like using the FS option more than once wont work, and causes either one or the other video to drop out, but the application is still running.
Update: Using these commands: 
`uv -d sdl:pos=0,0 127.0.0.1 -P 10000`
`uv -d sdl:pos=1920,0 127.0.0.1 -P 20000`
Causes the CPU to overload and not work.  But I use the mouse and move everything around, everything sits around 60% CPU usage.

The goal is to use the FS option and put it on any screen connected to the system without having to remotely login through vnc to handle it.

Using continuous build on Ubuntu 20

**Comment by MartinPulec** [comment] 2021-07-22 10:07
> The help reports that its a display index, I am assuming this is to be used to put the video output on to another display, but nothing seems to work. 1, :1, :1.0, HDMI-1 etc....

Yes. Correct is a use of single index - 0,1...n.

> Suggestions or is this a feature that is there, but not for use on linux?

No, I've just tried it and it seem to work for me with X11. Anyways, AFAIK it works for a single/merged display using Xinterama. If using separate X displays, using environment variable `DISPLAY` would perhaps do the job.
> 
> Update: seems like POS for position doesn't work either...

Again - I've just tested and it works for me. What environment do you use? I could imagine that some features may not work eg. under Wayland.

> Update: when passing the FS command, the POS command doesn't work. If I just use the sdl or gl command and POS option

GL doesn't seem to provide option for position, so I'll write about SDL2 only. I don't think that combination pos+fs makes any sense, pos+display has but that works for me.

> Update: Looks like using the FS option more than once wont work, and causes either one or the other video to drop out, but the application is still running.

You mean using 2 processes? But I think that this is a natural behavior.

> Update: Using these commands:
> `uv -d sdl:pos=0,0 127.0.0.1 -P 10000`
> `uv -d sdl:pos=1920,0 127.0.0.1 -P 20000`
> Causes the CPU to overload and not work. But I use the mouse and move everything around, everything sits around 60% CPU usage.

I am afraid that I don't understand the issue - doesn't work means exactly what?

> 
> The goal is to use the FS option and put it on any screen connected to the system without having to remotely login through vnc to handle it.
> 

Sure, but I guess that the above should work. at it works for me. Do you have some specific configuration and/or can you try from a U20.04 live medium? I'll try to test Wayland also.

**Comment by MartinPulec** [comment] 2021-07-22 15:01
[I've just pushed](https://github.com/CESNET/UltraGrid/actions/runs/1056549604)  an update that prints available display indices, it should be present in [the current AppImage](https://github.com/CESNET/UltraGrid/releases/download/continuous/UltraGrid-continuous-x86_64.AppImage).

**Comment by TheSashmo** [comment] 2021-07-22 15:30
Yes I see it now.  I will go back and test again.

**Comment by TheSashmo** [comment] 2021-07-22 17:44
So here is what I found.  I don't think its a bug, its just not obvious to dummies like me.

In other applications that I have worked with, i.e. VLC, you can use the full screen option and there is still decorations.

So one would think that you pass the command FS and NODECORATE.  But when doing that, the display index is not used.

Here is what I found:

`./UltraGrid-continuous-x86_64.AppImage -d sdl:display=0:nodecorate 127.0.0.1 -P 10000 (works)
./UltraGrid-continuous-x86_64.AppImage -d sdl:display=1:nodecorate 127.0.0.1 -P 10000 (works)

/UltraGrid-continuous-x86_64.AppImage -d sdl:fs:display=0:nodecorate 127.0.0.1 -P 10000 loads on screen 1
/UltraGrid-continuous-x86_64.AppImage -d sdl:fs:display=1:nodecorate 127.0.0.1 -P 10000 loads on screen 1 (obviously)`

It's not a bug, just something that needs to be taken under consideration when passing arguments to the application.

I will say that having the display index option is a HUGE asset.  This was a great add-on. 

Excuse my ignorance, but SDL vs GL....  Any documenation out there that you suggest I read to understand the value advantages or disadvantages of which to use.  I can see for sure that GL uses less CPU, while SDL uses much more.  I tested that by running two instances and there was about 25% > CPU usage in SDL.

**Comment by TheSashmo** [comment] 2021-07-22 19:46
I feel like I am turning this into a super long thread :(

I think this might be an operating system issue, but when trying to run another fullscreen i.e. I am scripting the system to run ultragrid after it boots, I can load the first instance on screen 1 in full screen, and once I load on screen 0, or vice versa, it dosn't matter the order, the other window minimizes. 

Easy to replicate.  Just try to run two commands 

```
./UltraGrid-continuous-x86_64.AppImage -d sdl:fs:display=0 127.0.0.1 -P 10000
./UltraGrid-continuous-x86_64.AppImage -d sdl:fs:display=1 127.0.0.1 -P 20000
```

The issue is the full screen option for sure because I can run them just fine when not using the fullscreen option.

**Comment by MartinPulec** [comment] 2021-07-26 09:24
Hi,

> So one would think that you pass the command FS and NODECORATE. But when doing that, the display index is not used.
> 
> Here is what I found:
> 
> `./UltraGrid-continuous-x86_64.AppImage -d sdl:display=0:nodecorate 127.0.0.1 -P 10000 (works)
> ./UltraGrid-continuous-x86_64.AppImage -d sdl:display=1:nodecorate 127.0.0.1 -P 10000 (works)
> 
> /UltraGrid-continuous-x86_64.AppImage -d sdl:fs:display=0:nodecorate 127.0.0.1 -P 10000 loads on screen 1
> /UltraGrid-continuous-x86_64.AppImage -d sdl:fs:display=1:nodecorate 127.0.0.1 -P 10000 loads on screen 1 (obviously)`
> 
> It's not a bug, just something that needs to be taken under consideration when passing arguments to the application.

I see, I can reproduce that as well. However it may be rather a SDL2 thing than UltraGrid's - the parameters are just passed. But I don't know it for sure. However, I don't see any advantage of using `nodecodrate` and `fs` - does passing `nodecorate` has some reason in addition to `fs`?

> 
> I will say that having the display index option is a HUGE asset. This was a great add-on.
> 
> Excuse my ignorance, but SDL vs GL.... Any documentation out there that you suggest so that I can read to understand the value advantages or disadvantages of which to use. I can see for sure that GL uses less CPU, while SDL uses much more. I tested that by running two instances and there was about 25% > CPU usage in SDL.

No, unfortunately there isn't any - it cannot be told in general. For _GL_ the situation is quite simple - the rendering is always HW-accelerated (except special cases). SDL2 has multiple backends for both window and renderer and generally it is also accelerated. But not all renderers are - "_software_" obviously isn't but also other may use some suboptimal pipeline. Taken just from the performance perspective, the _GL_ display is under normal circumstances a bit tweaked and is supposed to perform better.

**Comment by TheSashmo** [comment] 2021-07-27 00:00
> I see, I can reproduce that as well. However it may be rather a SDL2 thing than UltraGrid's - the parameters are just passed. But I don't know it for sure. However, I don't see any advantage of using `nodecodrate` and `fs` - does passing `nodecorate` has some reason in addition to `fs`?

Its just something from habbit from vlc and ffmpeg that you need to pass both to make sure there is no window decorations in fullscreen.  Like I said, its not a bug, just creates a different output if its passed.



> No, unfortunately there isn't any - it cannot be told in general. For _GL_ the situation is quite simple - the rendering is always HW-accelerated (except special cases). SDL2 has multiple backends for both window and renderer and generally it is also accelerated. But not all renderers are - "_software_" obviously isn't but also other may use some suboptimal pipeline. Taken just from the performance perspective, the _GL_ display is under normal circumstances a bit tweaked and is supposed to perform better.

Understood, thanks.

**Comment by TheSashmo** [comment] 2021-07-27 00:07
> > I can load the first instance on screen 1 in full screen, and once I load on screen 0, or vice versa, it dosn't matter the order, the other window minimizes.
> 
> I can confirm that behavior but I am afraid that it may be possible that X11 support only one full-screen window displayed at once, even though there are 2 displays. But just guessing. I can imagine these workarounds: 1) using only `nodecorate`; 2) using separate screens/servers (if possible)

Looks like gibhub shows this as my entry but edited by @MartinPulec interesting how that worked out.....

I am able to execute the fullscreen by hand so there can be two full screens at once, I belive the issue is how the fullscreen message is being sent to X11.

**Comment by MartinPulec** [comment] 2021-07-27 07:31
> Looks like gibhub shows this as my entry but edited by @MartinPulec interesting how that worked out.....

Ugh, interesting indeed. I've looked into the history of the post and seems really like my fault that I've clicked "edit" instead of "quote reply". I really don't recall but I'll trust that - sorry then, should be fixed now :)

**Comment by MartinPulec** [comment] 2021-07-27 07:48
Anyways, returning back to the post I've mistakenly edited - I can reproduce this with the AppImage but not with my own build (Ubuntu 20.04, thus SDL 2.0.14 vs 2.0.8 that is bundled in the AppImage). This leads me to believe that it has either been fixed (or workarounded) between those SDL2 revisions (UG code is the same).

Would you be interested to have it fixed? I guess that I can compile newer SDL2 version to the AppImage (it would require a little work and a little more build time).

**Comment by TheSashmo** [comment] 2021-07-27 14:20
Lovely I will test and let you know!

**Closed** 2021-07-27 14:25 UTC
