### ISSUE TITLE
Audio Scale issue

### ISSUE THREAD

**Issue by mondaufgrau** [CESNET/UltraGrid#25] opened 2019-07-17 09:51 UTC
Hi,

When I do some channel remapping on the receiver, if the sender sends some audio at reasonable volume (between -30db and -20db), and then nothing (or at least lower than -80db) for about 1minute30 or more, then some noise begin to increase on the receiver, and when the sender sends at normal volume again, the sound is awfully distorted.

After that, it takes around 1 minute to slowly go back to normal, but it never really goes back down to the initial level.

Setting --audio-scale none solve the problem.

**Comment by alatteri** [comment] 2019-07-17 13:23
What OS?

**Comment by mondaufgrau** [comment] 2019-07-17 13:26
Mac OS 10.13.6

**Comment by MartinPulec** [comment] 2020-08-07 12:08
Hi, thanks for reporting and sorry for a long delay. I was at first unsure how to replicate the issue.

I can confirm the issue with a material created by:

    curl -L 'https://www.dropbox.com/s/620qqip91g6td9t/Double%20Violin%20Concerto%201st%20Movement%20-%20J.S.%20Bach.mp3?dl=1' -o bach.mp3
    sox -v 0.5 bach.mp3 bach_trim.wav trim 0 120
    sox -n -c 2 -r 44100 -b 16 noise.wav synth 120 whitenoise vol 0.00005
    sox bach_trim.wav noise.wav out.wav

And then played with:

    /bin/uv -r alsa -s testcard:file=out.wav --audio-channel-map 0:0,1:0

The behavior is almost the same as you report, except that for the material above the level actually returns to "normal" value (I wouldn't say original since there is automatic scaling so this is relative). But this may be given by the character of the material (eg. spoken word vs. music like I used).

This is caused by automatic audio scaling. I'll perhaps add some threshold to the scaler.

**Comment by alatteri** [comment] 2020-08-07 12:58
Why would UG change the audio levels in a simple channel remapping scenario?  Should be same data, just channel swapped.

**Comment by MartinPulec** [comment] 2021-08-02 13:13
@alatteri Sorry, I've somehow missed your comment a year ago :) It depends - you meant something like `0:1,1:0`? Then it shouldn't indeed and currently it does, that is true. This is not intentional, there just will be needed some logic to check if there will be mixed 2 or more channels together which would require to guard the levels.

**Comment by MartinPulec** [comment] 2021-08-05 13:35
Ok, this should be fixed in the end with current code. There are 2 relevant changes that should now avoid the behavior:

1. audio scaling is disabled for output channels that doesn't mix 2 or more input channels (as @alatteri noted)
2. even though the auto scaler is working, it is more conservative - mainly there was low level increase, which has been removed. Therefor the audio scaler would currently usually not touch the signal at all unless not needed to avoid clipping.

**Comment by alatteri** [comment] 2021-08-05 14:07
Hi Martin,

Yes, that, but also sometimes we need to remap 5.1 audio since for some end devices the order is wrong.  We don't mix them, just swap them around.

> @alatteri Sorry, I've somehow missed your comment a year ago :) It depends - you meant something like `0:1,1:0`? Then it shouldn't indeed and currently it does, that is true. This is not intentional, there just will be needed some logic to check if there will be mixed 2 or more channels together which would require to guard the levels.

**Comment by MartinPulec** [comment] 2021-08-05 14:29
> Yes, that, but also sometimes we need to remap 5.1 audio since for some end devices the order is wrong. We don't mix them, just swap them around.

Sure, so as I have written above, in that case the signal is untouched from now.

**Closed** 2022-06-21 10:20 UTC
Labels: bug, needs-testing
