### ISSUE TITLE
Update preset options for NVENC

### ISSUE THREAD

**Issue by llamafilm** [CESNET/UltraGrid#119] opened 2020-12-14 23:18 UTC
I have installed libavcodec using Nvidia SDK 10.0.  Running Ultragrid with hevc_nvenc and default settings results in the following errors:

```
[hevc_nvenc @ 000000000b82a540] The selected preset is deprecated. Use p1 to p7 + -tune or fast/medium/slow.
[hevc_nvenc @ 000000000b82a540] Specified rc mode is deprecated.
[hevc_nvenc @ 000000000b82a540] Use -rc constqp/cbr/vbr, -tune and -multipass instead.
[hevc_nvenc @ 000000000b82a540] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set
[lavc] Could not open codec for pixel format p010le
```

The defaults in libavcodec.cpp should probably be updated to something like this.
```cpp
static constexpr const char *DEFAULT_NVENC_PRESET = "p5";
static constexpr const char *DEFAULT_NVENC_RC = "cbr";
```

**Comment by alatteri** [comment] 2020-12-14 23:19
I believe they have been updated in FFMPEG head.

**Comment by llamafilm** [comment] 2020-12-14 23:27
@alatteri FFmpeg works fine.  This code is part of UltraGrid.

**Comment by alatteri** [comment] 2020-12-14 23:28
Which version of FFMPEG?

**Comment by llamafilm** [comment] 2020-12-14 23:44
I built ffmpeg from git master but that doesn't really matter because these two params are defined in UltraGrid code.

**Comment by alatteri** [comment] 2021-01-03 05:03
I see this in the current code. I don't think it has been changed in awhile.  Maybe you are looking at old code?

```
static constexpr const char *DEFAULT_NVENC_PRESET = "llhq";
static constexpr const char *DEFAULT_NVENC_RC = "cbr_hq"; // cbr_ld_hq for equally sized frames
```

**Comment by MartinPulec** [comment] 2021-01-07 13:15
Hi @llamafilm, ok, good idea - that makes sense. The only problem is that currently only recent FFmpeg recognizes that options. On the other hand, there can be a fallback option with current values.

**Comment by MartinPulec** [comment] 2021-01-07 16:09
I've pushed modified version of your proposed solution, notes:

1. I've selected "p7" in the end - that should be equivalent to original "hq". Since the encoding is done in HW, I don't see a reason why not to use the best option by default (on CPU one would also need to consider the load).
2. I am also setting tune "ull" now (ultra low latency) - it will be needed to check if it doesn't cause pulsation (if you would be able it would be perfect - currently it would be a complicate for me since I am on a home-office now). If it does, perhaps 'll' would be better as a default.

The explicit _tune_ setting is actually required - it is the way to figure out if FFmpeg uses old or new values - even new FFmpeg may not support the new API if it was built with old NVENC headers. The problem is that validity of preset is not checked when set but would cause errors on runtime if the new one, _p7_, is not supported. That's why it is actually needed to set the tune to check, if the preset is supported (slightly crazy).

I am open to remarks - I think that the above described solution is reasonable. On the other hand, I didn't tested quality impact, impact on bit-rate stability etc.

**Comment by llamafilm** [comment] 2021-01-08 14:35
This sounds good to me.  I have been using `tune=hq` and am pretty happy with latency, but I will try to test `ull` soon.
I think p7 makes sense.  Surprisingly there is very little performance difference between the 7 presets.  I guess this would be more important if you try to run many instances of nvenc on the same card.

**Comment by MartinPulec** [comment] 2021-03-31 08:47
Just FYI, the Nvidia Codec SDK used for the build was just updated to _master_ (currently version 11).

**Comment by MartinPulec** [comment] 2021-06-21 07:43
Closing now because this is already implemented in UG master.

**Closed by MartinPulec** 2021-06-21 07:43 UTC
Labels: needs-testing
