### ISSUE TITLE
AAC encoder causes Segmentation Fault

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#80] opened 2020-08-19 20:06 UTC
Running UltraGrid 1.6+ (tags/continuous rev a76979ab built Aug 19 2020 14:47:12) On Ubuntu 18.04

Cannot get AAC to work anymore.
I keep getting repeated Error encoding frame. Error = -22 until the app crashes

Here is the command to run the encode
uv -t decklink:device=0 -c libavcodec:encoder=hevc_nvenc:bitrate=15M -s embedded --audio-codec AAC --audio-capture-format channels=2 -f rs:200:240 -f A:mult:3 --verbose -m 1390 10.0.0.1 -P 5004:5004:5006:5006 --control-port=8001 --param control-accept-global

Cuda - 11.0.3
Decklink - 11.6

Decklink card is a Duo 2
Nvidia Card is a P400

uv --audio-codec help

Supported audio codecs:
	FLAC
	AAC
	MP3
	G.722
	OPUS
	speex - unavailable
	u-law
	A-law
	PCM

ffmpeg -encoders
 A..... aac                  AAC (Advanced Audio Coding)
 A..... libfdk_aac           Fraunhofer FDK AAC (codec aac)

**Comment by alatteri** [comment] 2020-08-19 20:27
did you try specifying a bitrate for the audio?

**Comment by alatteri** [comment] 2020-08-19 20:33
you are missing an equal sign between audio-codec and AAC

**Comment by erichorwitz** [comment] 2020-08-19 20:45
I never had to specify bitrate before.... also the help doesn't show an equals sign anymore

Even with the testcard its not working....

uv -t testcard:pattern=bars -c libavcodec:encoder=hevc_nvenc:bitrate=15M -s testcard --audio-codec=AAC:bitrate=192k --audio-capture-format channels=2 -f rs:200:240 -f A:mult:3 --verbose -m 1390 10.0.0.1 -P 5004:5004:5006:5006 --control-port=8001 --param control-accept-global

**Comment by erichorwitz** [comment] 2020-08-19 20:50
PCM work fine

**Comment by MartinPulec** [comment] 2020-08-20 08:13
Hi, which build it is? Using current AppImage, I am not able to reproduce the issue in Ubuntu 18.04 ([log](https://github.com/CESNET/UltraGrid/files/5101617/log.txt) attached), I am using following command (same options as yours, skipping  the video part):

    ./UltraGrid-continuous-x86_64.AppImage  -s testcard --audio-codec=AAC:bitrate=192k \
       --audio-capture-format channels=2 -f A:mult:3 --verbose -m 1390

Can you please try it out?

Thanks,
Martin

**Comment by erichorwitz** [comment] 2020-08-20 14:59
Martin,

I was able to get this working with the AppImage. I still don't understand why my compile is not working. I didn't change anything from how I was compiling 1.5 and continuous up to the beginning of 1.6. 

When you compile are you also compiling ffmpeg/libavcodec before? Or are you using libraries provided by the distribution?

Eric

**Comment by alatteri** [comment] 2020-08-20 15:13
Hi Eric,

I wonder if it is similar to this issue?

https://github.com/CESNET/UltraGrid/issues/21

**Comment by erichorwitz** [comment] 2020-08-21 04:56
It doesn't seem to be... Its definitely something that is going on with how its getting compiled but I am not sure what's causing it. I have create a suite of scripts that auto download everything and compile the same way on fresh installs of ubuntu 18.04 minimal. The issue started happening recently. I even tried compiling the "1.6" release tag but that had the same problem. The issue started when I had to upgrade to cuda 11 from 10.2 and Blackmagic SDK11.6 from 11.5.

Is there anything I can provide to help troubleshoot?

**Comment by MartinPulec** [comment] 2020-08-25 14:04
Would it be possible to try a more minimal configuration?

If possible, I'd make sure that all relevant distro FFmpeg packages are removed, if possible, eg.:

    sudo apt-get remove 'libavcodec* libsws* libavutil*'

And then something like:

#### FFmpeg

    sudo apt-get build-dep ffmpeg
    git clone -b n4.3 https://git.ffmpeg.org/ffmpeg.git ffmpeg
    ./configure --prefix=$HOME/uv-build
    make install

#### UltraGrid

    git clone https://github.com/CESNET/UltraGrid.git ultragrid
    cd ultragrid
    export PKG_CONFIG_PATH=$HOME/uv-build/lib/pkg-config
    ./autogen.sh --enable-libavcodec
    make
    export LD_LIBRARY_PATH="$HOME/uv-build/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
    ./bin/uv -s testcard --audio-codec AAC

**Comment by MartinPulec** [comment] 2020-08-25 19:26
UPDATE 1: I've at least fixed the crash (although it won't fix the problem)

UPDATE 2: I was also able to reproduce the problem, but after I removed the distro packages, it disappeared. I guess that there is a clash of distro headers and newer libs. Perhaps it would help to set `CPATH` to `$HOME/uv-build/include` if not possible to uninstall the headers.

But it is possible that there is a problem still, but I was not able to reproduce it yet.

**Comment by erichorwitz** [comment] 2020-08-25 19:36
Martin,

Thank you SO much for continuing to look into this. I was also able to build Ultragrid with your recommended steps including removing the distro packages and AAC worked... I am going to try the full build by removing the distro packages before installing everything else...

**Comment by MartinPulec** [comment] 2021-06-21 07:42
Hi Eric, so I am closing the issue for now if you do not have any further observations.

**Closed by MartinPulec** 2021-06-21 07:42 UTC
Labels: unable-to-reproduce
